name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gor:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: action/setup-node@v1
          with:
            node-version: 18.14.0
            registry-url: https://npm.pkg.github.com/
            scope: '@abdallahmoubarak'
        - run: npm install
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
